### ISSUE TITLE
Send message in chat when someone follows/subscribes

### ISSUE THREAD

**Issue by JamyDev** [WatchBeam/widgets#15]
Needs discussing on how to best implement this as FE can easily check the liveloading events and display a message.

**Comment by connor4312** [comment]
Just put in a widget that creates a (or uses an existing) pubsub connection `.on('channel')` that sends some specific event to connected clients when there's a `live:channel:<id>:follow` or `live:channel:<id>:subscribe`. Actually... the frontend already listens to these events, it could just put something in chat directly.

**Comment by JamyDev** [comment]
Moving to FE as this is more of an frontend issue :)
